Repository jenkins-x-plugins/jx-verify, pull requests merged in 2020-11, with the labels that each got.

#49 docs: regen
  .goreleaser.yml
  docs/cmd/jx-verify.md
  docs/cmd/jx-verify_behavior.md
  docs/cmd/jx-verify_dependencies.md
  docs/cmd/jx-verify_dns.md
  docs/cmd/jx-verify_environments.md
  docs/cmd/jx-verify_git.md
  docs/cmd/jx-verify_ingress.md
  docs/cmd/jx-verify_install.md
  docs/cmd/jx-verify_packages.md
  docs/cmd/jx-verify_pod.md
  docs/cmd/jx-verify_pod_count.md
  docs/cmd/jx-verify_pod_ready.md
  docs/cmd/jx-verify_preinstall.md
  docs/cmd/jx-verify_requirements.md
  docs/cmd/jx-verify_tls.md
  docs/cmd/jx-verify_url.md
  docs/cmd/jx-verify_values.md
  docs/cmd/jx-verify_version.md
  docs/cmd/jx-verify_webhooks.md
  docs/man/man1/jx-verify-behavior.1
  docs/man/man1/jx-verify-dependencies.1
  docs/man/man1/jx-verify-dns.1
  docs/man/man1/jx-verify-environments.1
  docs/man/man1/jx-verify-git.1
  docs/man/man1/jx-verify-ingress.1
  docs/man/man1/jx-verify-install.1
  docs/man/man1/jx-verify-packages.1
  docs/man/man1/jx-verify-pod-count.1
  docs/man/man1/jx-verify-pod-ready.1
  docs/man/man1/jx-verify-pod.1
  docs/man/man1/jx-verify-preinstall.1
  docs/man/man1/jx-verify-requirements.1
  docs/man/man1/jx-verify-tls.1
  docs/man/man1/jx-verify-url.1
  docs/man/man1/jx-verify-values.1
  docs/man/man1/jx-verify-version.1
  docs/man/man1/jx-verify-webhooks.1
  docs/man/man1/jx-verify.1
Labels: approved, size/XXL

#48 chore: refactor out v2 jx dependency
  jenkins-x.yml
  pkg/cmd/ingress/ingress.go
Labels: approved, lgtm, ok-to-test, size/M

#51 fix: add verify install command
  go.mod
  pkg/cmd/ingress/ingress.go
  pkg/cmd/install/install.go
  pkg/cmd/root.go
Labels: approved, size/L

#52 fix: lets add .nip.io so we can use ingress domains with DNS sub domains
  pkg/cmd/ingress/ingress.go
Labels: approved, size/XS
