Repository jenkins-x-plugins/jx-verify, pull requests merged in 2020-12, with the labels that each got.

#62 refactor: remove old v2 requirements
  go.mod
  go.sum
  pkg/cmd/ingress/ingress.go
Labels: approved, size/M

#64 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
Labels: approved, size/XS

#65 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot

#68 fix: use latest nginx name
  pkg/cmd/ingress/ingress.go
  pkg/cmd/install/install.go
  promote.sh
Labels: approved, size/XS

#74 chore: bump jx-api version to stop requirements schema moans
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS
