Repository jenkins-x-plugins/jx-verify, pull requests merged in 2021-06, with the labels that each got.

#160 feat: allow pod annotations to be specified
  charts/jx-verify/templates/job.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#161 fix: add random name
  charts/jx-verify/templates/_helpers.tpl
  charts/jx-verify/templates/job.yaml
Labels: approved, size/XS

#162 fix: lets use a fixed SA/Role name
  charts/jx-verify/templates/_helpers.tpl
  charts/jx-verify/templates/job-rb.yaml
  charts/jx-verify/templates/job-role.yaml
  charts/jx-verify/templates/job-sa.yaml
  charts/jx-verify/templates/job.yaml
Labels: approved, size/S
