Repository jenkins-x-plugins/jx-verify, pull requests merged in 2021-01, with the labels that each got.

#87 chore: bump jx-api version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#90 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#92 chore: bump jx-api and lets not fail on requirements validation failures so we can be a bit more lenient when adding new requirements
  go.mod
  go.sum
  pkg/cmd/ingress/ingress.go
Labels: approved, size/S

#93 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#94 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#101 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#102 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#103 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#104 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/L, updatebot

#113 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
