Repository jenkins-x-plugins/jx-verify, pull requests merged in 2021-02, with the labels that each got.

#121 fix: add a verify pods command
  go.mod
  go.sum
  pkg/cmd/pods/pods.go
  pkg/cmd/pods/pods_test.go
  pkg/cmd/root.go
Labels: approved, size/L

#122 fix: add chart for verify pods
  charts/jx-verify/.helmignore
  charts/jx-verify/Chart.yaml
  charts/jx-verify/Makefile
  charts/jx-verify/README.md.gotmpl
  charts/jx-verify/templates/NOTES.txt
  charts/jx-verify/templates/_helpers.tpl
  charts/jx-verify/templates/job-rb.yaml
  charts/jx-verify/templates/job-role.yaml
  charts/jx-verify/templates/job-sa.yaml
  charts/jx-verify/templates/job.yaml
  charts/jx-verify/values.yaml
  go.mod
  go.sum
Labels: approved, size/L

#124 fix: added verify job step
  docs/cmd/jx-verify.md
  docs/cmd/jx-verify_ingress.md
  docs/cmd/jx-verify_install.md
  docs/cmd/jx-verify_job.md
  docs/cmd/jx-verify_pods.md
  docs/cmd/jx-verify_tls.md
  docs/cmd/jx-verify_version.md
  docs/man/man1/jx-verify-ingress.1
  docs/man/man1/jx-verify-install.1
  docs/man/man1/jx-verify-job.1
  docs/man/man1/jx-verify-pods.1
  docs/man/man1/jx-verify.1
  go.mod
  pkg/cmd/job/job.go
  pkg/cmd/job/job_test.go
  pkg/cmd/root.go
Labels: approved, size/XL

#125 chore: fix verify job
  pkg/cmd/job/job.go
Labels: approved, size/M

#126 chore: polish output
  go.sum
  pkg/cmd/job/job.go
Labels: approved, size/S

#128 chore: if domain is change.me or empty lets switch it to nip.io
  pkg/cmd/ingress/ingress.go
Labels: approved, size/XS

#130 fix: allow the verify job to wait for a job to exist
  go.mod
  go.sum
  pkg/cmd/job/job.go
Labels: approved, size/M

#131 chore: better logic for waiting for job to exist
  pkg/cmd/job/job.go
Labels: approved, size/XS

#133 chore: fix waiting for job
  pkg/cmd/job/job.go
Labels: approved, size/XS

#134 fix: add flags so we can avoid failing an actual Job
  docs/cmd/jx-verify.md
  docs/cmd/jx-verify_ingress.md
  docs/cmd/jx-verify_install.md
  docs/cmd/jx-verify_job.md
  docs/cmd/jx-verify_pods.md
  docs/cmd/jx-verify_tls.md
  docs/cmd/jx-verify_version.md
  docs/man/man1/jx-verify-job.1
  go.mod
  go.sum
  pkg/cmd/job/job.go
Labels: approved, size/L

#135 chore: wait for at least 2 ready pods before terminating
  docs/cmd/jx-verify_pods.md
  docs/man/man1/jx-verify-pods.1
  pkg/cmd/pods/pods.go
Labels: approved, size/XS

#136 chore: lets add a step to verify k8s context
  docs/cmd/jx-verify.md
  docs/cmd/jx-verify_context.md
  docs/man/man1/jx-verify-context.1
  docs/man/man1/jx-verify.1
  go.mod
  pkg/cmd/ctx/ctx.go
  pkg/cmd/root.go
Labels: approved, size/L

#138 chore: default the domain to the IP address
  go.mod
  go.sum
  pkg/cmd/ingress/ingress.go
Labels: approved, size/S

#140 fix: lets tell kapp not to wait
  charts/jx-verify/templates/job.yaml
  go.mod
  go.sum
Labels: approved, size/S

#141 fix: fix the selectors
  charts/jx-verify/templates/job.yaml
Labels: approved, size/XS

#142 chore: fix selector
  charts/jx-verify/templates/job.yaml
Labels: approved, size/XS

#143 fix: fix selector
  charts/jx-verify/templates/job.yaml
Labels: approved, size/XS

#144 fix: work better with kapp
  charts/jx-verify/templates/job.yaml
Labels: approved, size/XS
